"""Add security fields for IP blocking and permanent lockout

Revision ID: 1f522fd807f9
Revises: f8b970e5f6f8
Create Date: 2025-12-15 12:09:28.418210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '1f522fd807f9'
down_revision = 'f8b970e5f6f8'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    inspector = sa.inspect(op.get_bind())

    # FIRST check if table exists
    if table_name not in inspector.get_table_names():
        return False

    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create blocked_ips table only if it doesn't exist
    if not table_exists('blocked_ips'):
        op.create_table('blocked_ips',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ip_address', sa.String(length=45), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=True),
        sa.Column('failed_attempts', sa.Integer(), nullable=True),
        sa.Column('blocked_at', sa.DateTime(), nullable=False),
        sa.Column('blocked_until', sa.DateTime(), nullable=True),
        sa.Column('is_permanent', sa.Boolean(), nullable=True),
        sa.Column('blocked_by', sa.Integer(), nullable=True),
        sa.Column('unblocked_by', sa.Integer(), nullable=True),
        sa.Column('unblocked_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['unblocked_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_blocked_ips_ip_address'), ['ip_address'], unique=False)

    # Add columns to users table only if they don't exist
    with op.batch_alter_table('users', schema=None) as batch_op:
        if not column_exists('users', 'is_permanently_locked'):
            batch_op.add_column(sa.Column('is_permanently_locked', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        if not column_exists('users', 'permanently_locked_at'):
            batch_op.add_column(sa.Column('permanently_locked_at', sa.DateTime(), nullable=True))
        if not column_exists('users', 'permanently_locked_reason'):
            batch_op.add_column(sa.Column('permanently_locked_reason', sa.String(length=255), nullable=True))
        if not column_exists('users', 'last_failed_login_ip'):
            batch_op.add_column(sa.Column('last_failed_login_ip', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_failed_login_ip')
        batch_op.drop_column('permanently_locked_reason')
        batch_op.drop_column('permanently_locked_at')
        batch_op.drop_column('is_permanently_locked')

    with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_ips_ip_address'))

    op.drop_table('blocked_ips')
    # ### end Alembic commands ###
