"""Initial database schema

Revision ID: f8b970e5f6f8
Revises: 
Create Date: 2025-12-12 08:32:56.327727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b970e5f6f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('packets', sa.Integer(), nullable=True),
    sa.Column('flows', sa.Integer(), nullable=True),
    sa.Column('alerts', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=False),
    sa.Column('class_3', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('in_bytes', sa.Integer(), nullable=True),
    sa.Column('out_bytes', sa.Integer(), nullable=True),
    sa.Column('in_pkts', sa.Integer(), nullable=True),
    sa.Column('out_pkts', sa.Integer(), nullable=True),
    sa.Column('flow_duration_ms', sa.Integer(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_created_attack', ['created_at', 'attack_type'], unique=False)
        batch_op.create_index('idx_alerts_severity', ['severity', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_attack_type'), ['attack_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_dst_ip'), ['dst_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_src_ip'), ['src_ip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_src_ip'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_dst_ip'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_attack_type'))
        batch_op.drop_index('idx_alerts_severity')
        batch_op.drop_index('idx_alerts_created_attack')

    op.drop_table('alerts')
    op.drop_table('traffic_daily')
    # ### end Alembic commands ###
